@tool
extends ResourceFormatLoader
class_name KS_ResourceLoader

## Loads source .ks files as cached KND_Shot script resources.
##
## EditorImportPlugin resources are intentionally avoided: Godot treats imported
## resources as read-only and forces "Save As" in the native Script Editor. A
## format loader preserves the original source path, while exported projects still
## use the encrypted binary remap generated by KND_ScriptExportPlugin.


func _get_recognized_extensions() -> PackedStringArray:
	return PackedStringArray(["ks"])


func _handles_type(type: StringName) -> bool:
	return type in [&"", &"Resource", &"Script", &"ScriptExtension", &"KND_Shot"]


func _get_resource_type(path: String) -> String:
	if path.get_extension().to_lower() == "ks":
		return "Script"
	return ""


func _get_resource_script_class(_path: String) -> String:
	return ""


func _load(
	path: String,
	original_path: String,
	_use_sub_threads: bool,
	_cache_mode: int,
) -> Variant:
	var source_path := original_path if not original_path.is_empty() else path
	var compiler := KS_Compiler.new()
	compiler.set_console_output_enabled(false)
	var shot := compiler.compile_file(path)
	if shot == null:
		# Invalid source must remain editable. Returning an empty script document in
		# the editor lets the native diagnostics UI explain and repair the error.
		if Engine.is_editor_hint():
			var editable_shot := KND_Shot.new()
			editable_shot.ks_path = source_path
			var file := FileAccess.open(path, FileAccess.READ)
			if file != null:
				editable_shot.set_source_code(file.get_as_text())
			return editable_shot
		for error: String in compiler.get_errors():
			push_error(error)
		return ERR_PARSE_ERROR
	shot.ks_path = source_path
	return shot
